(function(){var K,T,n,l,U,B,C,f,V,W,L,X,Y,t,Z,q,D,E,u,F,M,N,p,aa,r,h,G,O,ba,z,P,H,m,x,Q,v,I,R,J,ca,S,ga,da,A=[].slice,ea={}.hasOwnProperty,fa=function(a,b){function d(){this.constructor=a}for(var c in b)ea.call(b,c)&&(a[c]=b[c]);d.prototype=b.prototype;a.prototype=new d;a.__super__=b.prototype;return a},ha=[].indexOf||function(a){for(var b=0,d=this.length;b<d;b++)if(b in this&&this[b]===a)return b;return-1};n={catchupTime:100,initialRate:.03,minTime:250,ghostTime:100,maxProgressPerFrame:20,easeFactor:1.25,
startOnPageLoad:!1,restartOnPushState:!0,restartOnRequestAfter:500,target:"body",elements:{checkInterval:100,selectors:["body"]},eventLag:{minSamples:10,sampleCount:3,lagThreshold:3},ajax:{trackMethods:["GET"],trackWebSockets:!0,ignoreURLs:[]}};r=function(){var a;return null!=(a="undefined"!==typeof performance&&null!==performance?"function"===typeof performance.now?performance.now():void 0:void 0)?a:+new Date};G=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;E=window.cancelAnimationFrame||window.mozCancelAnimationFrame;null==G&&(G=function(a){return setTimeout(a,50)},E=function(a){return clearTimeout(a)});ba=function(a){var b,d;b=r();d=function(){var c;c=r()-b;return 33<=c?(b=r(),a(c,function(){return G(d)})):setTimeout(d,33-c)};return d()};O=function(){var a,b,d;d=arguments[0];b=arguments[1];a=3<=arguments.length?A.call(arguments,2):[];return"function"===typeof d[b]?d[b].apply(d,a):d[b]};u=function(){var a,b,d,c,e,k,g;
b=arguments[0];c=2<=arguments.length?A.call(arguments,1):[];k=0;for(g=c.length;k<g;k++)if(d=c[k])for(a in d)ea.call(d,a)&&(e=d[a],null!=b[a]&&"object"===typeof b[a]&&null!=e&&"object"===typeof e?u(b[a],e):b[a]=e);return b};Z=function(a){var b,d,c,e,k;e=d=b=0;for(k=a.length;e<k;e++)c=a[e],d+=Math.abs(c),b++;return d/b};l=function(){function a(){}a.prototype.on=function(b,a,c,e){var k;null==e&&(e=!1);null==this.bindings&&(this.bindings={});null==(k=this.bindings)[b]&&(k[b]=[]);return this.bindings[b].push({handler:a,
ctx:c,once:e})};a.prototype.once=function(b,a,c){return this.on(b,a,c,!0)};a.prototype.off=function(b,a){var c,e;if(null!=(null!=(c=this.bindings)?c[b]:void 0)){if(null==a)return delete this.bindings[b];c=0;for(e=[];c<this.bindings[b].length;)this.bindings[b][c].handler===a?e.push(this.bindings[b].splice(c,1)):e.push(c++);return e}};a.prototype.trigger=function(){var b,a,c,e,k,g,f;c=arguments[0];b=2<=arguments.length?A.call(arguments,1):[];if(null!=(a=this.bindings)&&a[c]){k=0;for(f=[];k<this.bindings[c].length;)g=
this.bindings[c][k],e=g.handler,a=g.ctx,g=g.once,e.apply(null!=a?a:this,b),g?f.push(this.bindings[c].splice(k,1)):f.push(k++);return f}};return a}();f=window.Pace||{};window.Pace=f;u(f,l.prototype);h=f.options=u({},n,window.paceOptions,function(a,b){var d;null==a&&(a="options");null==b&&(b=!0);if(d=document.querySelector("[data-pace-"+a+"]")){d=d.getAttribute("data-pace-"+a);if(!b)return d;try{return JSON.parse(d)}catch(c){return"undefined"!==typeof console&&null!==console?console.error("Error parsing inline pace options",
c):void 0}}}());S=["ajax","document","eventLag","elements"];l=0;for(B=S.length;l<B;l++)m=S[l],!0===h[m]&&(h[m]=n[m]);C=function(a){function b(){return ga=b.__super__.constructor.apply(this,arguments)}fa(b,a);return b}(Error);T=function(){function a(){this.progress=0}a.prototype.getElement=function(){var b;if(null==this.el){b=document.querySelector(h.target);if(!b)throw new C;this.el=document.createElement("div");this.el.className="pace pace-active";document.body.className=document.body.className.replace(/pace-done/g,
"");document.body.className+=" pace-running";this.el.innerHTML='<div class="pace-progress">\n  <div class="pace-progress-inner"></div>\n</div>\n<div class="pace-activity"></div>';null!=b.firstChild?b.insertBefore(this.el,b.firstChild):b.appendChild(this.el)}return this.el};a.prototype.finish=function(){var b;b=this.getElement();b.className=b.className.replace("pace-active","");b.className+=" pace-inactive";document.body.className=document.body.className.replace("pace-running","");return document.body.className+=
" pace-done"};a.prototype.update=function(b){this.progress=b;return this.render()};a.prototype.destroy=function(){try{this.getElement().parentNode.removeChild(this.getElement())}catch(b){C=b}return this.el=void 0};a.prototype.render=function(){var b,a,c,e,k,g;if(null==document.querySelector(h.target))return!1;b=this.getElement();c="translate3d(100%, "+(100-this.progress)+"%, 0)";g=["webkitTransform","msTransform","transform"];e=0;for(k=g.length;e<k;e++)a=g[e],b.children[0].style[a]=c;if(!this.lastRenderedProgress||
this.lastRenderedProgress|0!==this.progress|0)b.children[0].setAttribute("data-progress-text",""+(this.progress|0)+"%"),100<=this.progress?a="99":(a=10>this.progress?"0":"",a+=this.progress|0),b.children[0].setAttribute("data-progress",""+a);return this.lastRenderedProgress=this.progress};a.prototype.done=function(){return 100<=this.progress};return a}();n=function(){function a(){this.bindings={}}a.prototype.trigger=function(b,a){var c,e,k,g,f;if(null!=this.bindings[b]){g=this.bindings[b];f=[];e=
0;for(k=g.length;e<k;e++)c=g[e],f.push(c.call(this,a));return f}};a.prototype.on=function(b,a){var c;null==(c=this.bindings)[b]&&(c[b]=[]);return this.bindings[b].push(a)};return a}();R=window.XMLHttpRequest;I=window.XDomainRequest;v=window.WebSocket;F=function(a,b){var d,c;c=[];for(d in b.prototype)try{null==a[d]&&"function"!==typeof b[d]?"function"===typeof Object.defineProperty?c.push(Object.defineProperty(a,d,{get:function(){return b.prototype[d]},configurable:!0,enumerable:!0})):c.push(a[d]=
b.prototype[d]):c.push(void 0)}catch(e){}return c};p=[];f.ignore=function(){var a,b;b=arguments[0];a=2<=arguments.length?A.call(arguments,1):[];p.unshift("ignore");a=b.apply(null,a);p.shift();return a};f.track=function(){var a,b;b=arguments[0];a=2<=arguments.length?A.call(arguments,1):[];p.unshift("track");a=b.apply(null,a);p.shift();return a};H=function(a){var b;null==a&&(a="GET");return"track"===p[0]?"force":!p.length&&h.ajax&&("socket"===a&&h.ajax.trackWebSockets||(b=a.toUpperCase(),0<=ha.call(h.ajax.trackMethods,
b)))?!0:!1};V=function(a){function b(){var a,c=this;b.__super__.constructor.apply(this,arguments);a=function(a){var b;b=a.open;return a.open=function(d,f,h){H(d)&&c.trigger("request",{type:d,url:f,request:a});return b.apply(a,arguments)}};window.XMLHttpRequest=function(b){b=new R(b);a(b);return b};try{F(window.XMLHttpRequest,R)}catch(e){}if(null!=I){window.XDomainRequest=function(){var b;b=new I;a(b);return b};try{F(window.XDomainRequest,I)}catch(e){}}if(null!=v&&h.ajax.trackWebSockets){window.WebSocket=
function(b,a){var d;d=null!=a?new v(b,a):new v(b);H("socket")&&c.trigger("request",{type:"socket",url:b,protocols:a,request:d});return d};try{F(window.WebSocket,v)}catch(e){}}}fa(b,a);return b}(n);J=null;M=function(){null==J&&(J=new V);return J};P=function(a){var b,d,c,e;e=h.ajax.ignoreURLs;d=0;for(c=e.length;d<c;d++)if(b=e[d],"string"===typeof b){if(-1!==a.indexOf(b))return!0}else if(b.test(a))return!0;return!1};M().on("request",function(a){var b,d,c,e;e=a.type;c=a.request;if(!(P(a.url)||f.running||
!1===h.restartOnRequestAfter&&"force"!==H(e)))return d=arguments,b=h.restartOnRequestAfter||0,"boolean"===typeof b&&(b=0),setTimeout(function(){var b,a,h,w;if("socket"===e?2>c.readyState:0<(b=c.readyState)&&4>b){f.restart();h=f.sources;w=[];b=0;for(a=h.length;b<a;b++)if(m=h[b],m instanceof K){m.watch.apply(m,d);break}else w.push(void 0);return w}},b)});K=function(){function a(){var b=this;this.elements=[];M().on("request",function(){return b.watch.apply(b,arguments)})}a.prototype.watch=function(b){var a,
c;c=b.type;a=b.request;if(!P(b.url))return b="socket"===c?new X(a):new Y(a),this.elements.push(b)};return a}();Y=function(){return function(a){var b,d,c,e,f,g=this;this.progress=0;if(null!=window.ProgressEvent)for(a.addEventListener("progress",function(b){return b.lengthComputable?g.progress=100*b.loaded/b.total:g.progress+=(100-g.progress)/2},!1),f=["load","abort","timeout","error"],d=0,c=f.length;d<c;d++)b=f[d],a.addEventListener(b,function(){return g.progress=100},!1);else e=a.onreadystatechange,
a.onreadystatechange=function(){var b;0===(b=a.readyState)||4===b?g.progress=100:3===a.readyState&&(g.progress=50);return"function"===typeof e?e.apply(null,arguments):void 0}}}();X=function(){return function(a){var b,d,c,e,f=this;this.progress=0;e=["error","open"];d=0;for(c=e.length;d<c;d++)b=e[d],a.addEventListener(b,function(){return f.progress=100},!1)}}();l=function(){return function(a){var b,d,c;null==a&&(a={});this.elements=[];null==a.selectors&&(a.selectors=[]);c=a.selectors;b=0;for(d=c.length;b<
d;b++)a=c[b],this.elements.push(new U(a))}}();U=function(){function a(b){this.selector=b;this.progress=0;this.check()}a.prototype.check=function(){var b=this;return document.querySelector(this.selector)?this.done():setTimeout(function(){return b.check()},h.elements.checkInterval)};a.prototype.done=function(){return this.progress=100};return a}();n=function(){function a(){var b,a,c=this;this.progress=null!=(a=this.states[document.readyState])?a:100;b=document.onreadystatechange;document.onreadystatechange=
function(){null!=c.states[document.readyState]&&(c.progress=c.states[document.readyState]);return"function"===typeof b?b.apply(null,arguments):void 0}}a.prototype.states={loading:0,interactive:50,complete:100};return a}();B=function(){return function(){var a,b,d,c,e,f=this;a=this.progress=0;e=[];c=0;d=r();b=setInterval(function(){var g;g=r()-d-50;d=r();e.push(g);e.length>h.eventLag.sampleCount&&e.shift();a=Z(e);return++c>=h.eventLag.minSamples&&a<h.eventLag.lagThreshold?(f.progress=100,clearInterval(b)):
f.progress=3/(a+3)*100},50)}}();L=function(){function a(b){this.source=b;this.last=this.sinceLastUpdate=0;this.rate=h.initialRate;this.progress=this.lastProgress=this.catchup=0;null!=this.source&&(this.progress=O(this.source,"progress"))}a.prototype.tick=function(b,a){null==a&&(a=O(this.source,"progress"));100<=a&&(this.done=!0);a===this.last?this.sinceLastUpdate+=b:(this.sinceLastUpdate&&(this.rate=(a-this.last)/this.sinceLastUpdate),this.catchup=(a-this.progress)/h.catchupTime,this.sinceLastUpdate=
0,this.last=a);a>this.progress&&(this.progress+=this.catchup*b);this.progress+=(1-Math.pow(this.progress/100,h.easeFactor))*this.rate*b;this.progress=Math.min(this.lastProgress+h.maxProgressPerFrame,this.progress);this.progress=Math.max(0,this.progress);return this.lastProgress=this.progress=Math.min(100,this.progress)};return a}();D=t=Q=q=z=x=null;f.running=!1;N=function(){if(h.restartOnPushState)return f.restart()};null!=window.history.pushState&&(ca=window.history.pushState,window.history.pushState=
function(){N();return ca.apply(window.history,arguments)});null!=window.history.replaceState&&(da=window.history.replaceState,window.history.replaceState=function(){N();return da.apply(window.history,arguments)});W={ajax:K,elements:l,document:n,eventLag:B};(aa=function(){var a,b,d,c,e;f.sources=x=[];e=["ajax","elements","document","eventLag"];b=0;for(c=e.length;b<c;b++)a=e[b],!1!==h[a]&&x.push(new W[a](h[a]));a=null!=(d=h.extraSources)?d:[];d=0;for(b=a.length;d<b;d++)m=a[d],x.push(new m(h));f.bar=
q=new T;z=[];return Q=new L})();f.stop=function(){f.trigger("stop");f.running=!1;q.destroy();D=!0;null!=t&&("function"===typeof E&&E(t),t=null);return aa()};f.restart=function(){f.trigger("restart");f.stop();return f.start()};f.go=function(){var a;f.running=!0;q.render();a=r();D=!1;return t=ba(function(b,d){var c,e,k,g,y,w,l,n,p,t,u,v;c=l=0;e=!0;g=n=0;for(t=x.length;n<t;g=++n)for(m=x[g],w=null!=z[g]?z[g]:z[g]=[],g=null!=(v=m.elements)?v:[m],y=p=0,u=g.length;p<u;y=++p)k=g[y],k=null!=w[y]?w[y]:w[y]=
new L(k),e&=k.done,k.done||(c++,l+=k.tick(b));q.update(Q.tick(b,l/c));return q.done()||e||D?(q.update(100),f.trigger("done"),setTimeout(function(){f.running=!1;return f.trigger("hide")},Math.max(h.ghostTime,Math.max(h.minTime-(r()-a),0)))):d()})};f.start=function(a){u(h,a);f.running=!0;try{q.render()}catch(b){C=b}return document.querySelector(".pace")?(f.trigger("start"),f.go()):setTimeout(f.start,50)};"function"===typeof define&&define.amd?define(["pace"],function(){return f}):"object"===typeof exports?
module.exports=f:h.startOnPageLoad&&f.start();$(function(){$("[data-typer-targets]").typer();$(window).resize(function(){$(".thumb").hasClass("open")&&$(".thumb.open").css("top",$(window).scrollTop())});$("#hello .link").click(function(){$("#about").addClass("open");$("html, body").animate({scrollTop:$("#about").offset().top},1E3);$(".close-about").click(function(){$("#about").removeClass("open")})});var a,b=0,d;$(".thumb").scroll(function(){a=!0});setInterval(function(){if(a){var c=d.offset().top-
$(window).scrollTop();c>b?(c>=-500+$(".back").outerHeight()&&$(".x").removeClass("dark"),d.find(".back.close-bottom").offset().top>$(".thumb.open").offset().top+$(window).height()&&(d.find(".back.close-top").addClass("loaded"),$(".pace-inactive").removeClass("pace-hidden"))):d.find(".back.close-bottom").offset().top<=$(".thumb.open").offset().top+$(window).height()?(d.find(".back.close-top").removeClass("loaded"),$(".pace-inactive").addClass("pace-hidden")):c<-500+$(".back").outerHeight()&&$(".x").addClass("dark");
b=c;a=!1}},250);$("iframe").mouseover=function(){$(".thumb.open").style.overflow="hidden";cosonle.log("hiding scroll")};$("iframe").mouseout=function(){$(".thumb.open").style.overflow="auto";console.log("unhiding")};$(".thumb").click(function(b){var a=$(this),h=a.data("project"),g=a.find(".story"),l=""+h+".php";$(b.target).hasClass("close-top")?(a.find(".back.close-top").first().removeClass("loaded"),g.animate({marginTop:$(window).scrollTop()-g.offset().top},700),$(".intro").removeClass("loaded"),
$(".pace-inactive").addClass("pace-hidden"),setTimeout(function(){a.removeAttr("style");a.removeClass("open");a.addClass("closed");g.removeClass("open");$("body").removeClass("noScroll");setTimeout(function(){g.html("")},200)},1E3)):$(b.target).hasClass("close-bottom")?(g.animate({marginTop:-g.height()},700),setTimeout(function(){g.html("");a.removeAttr("style");a.removeClass("open");a.addClass("closed");$("body").removeClass("noScroll")},1E3)):$(".thumb").hasClass("open")||($(".story").removeClass("main"),
$(".thumb").removeClass("main"),$windowTop=$(window).scrollTop(),a.addClass("open"),a.removeClass("closed"),$(".thumb.open").css("top",$windowTop),g.removeAttr("style"),g.addClass("open"),$("body").addClass("noScroll"),d=$(".thumb.open").find(".story"),setTimeout(function(){f.restart();g.load(l);$.ajax({url:l,success:function(b){g.html(b);$(document).ajaxComplete(function(){setTimeout(function(){q.finish();a.find(".back.close-top").first().addClass("loaded");a.find(".intro").first().addClass("loaded")},
2E3)})}})},1E3))})})}).call(this);