(function(d,e,m,f){(function(a){for(var c=a.length,g=d("head");c--;)0===g.has("."+a[c]).length&&g.append('<meta class="'+a[c]+'" />')})("foundation-mq-small foundation-mq-medium foundation-mq-large foundation-mq-xlarge foundation-mq-xxlarge foundation-data-attribute-namespace".split(" "));d(function(){"undefined"!==typeof FastClick&&"undefined"!==typeof m.body&&FastClick.attach(m.body)});var l=function(a,c){if("string"===typeof a){if(c){var g;if(c.jquery){if(g=c[0],!g)return c}else g=c;return d(g.querySelectorAll(a))}return d(m.querySelectorAll(a))}return d(a,
c)},k=function(a){var c=[];a||c.push("data");0<this.namespace.length&&c.push(this.namespace);c.push(this.name);return c.join("-")},t=function(a){a=a.split("-");for(var c=a.length,g=[];c--;)0!==c?g.push(a[c]):0<this.namespace.length?g.push(this.namespace,a[c]):g.push(a[c]);return g.reverse().join("-")},b=function(a,c){var g=this,b=!l(this).data(this.attr_name(!0));if("string"===typeof a)return this[a].call(this,c);l(this.scope).is("["+this.attr_name()+"]")?(l(this.scope).data(this.attr_name(!0)+"-init",
d.extend({},this.settings,c||a,this.data_options(l(this.scope)))),b&&this.events(this.scope)):l("["+this.attr_name()+"]",this.scope).each(function(){var b=!l(this).data(g.attr_name(!0)+"-init");l(this).data(g.attr_name(!0)+"-init",d.extend({},g.settings,c||a,g.data_options(l(this))));b&&g.events(this)})},n=function(a,c){function g(){c(a[0])}function b(){this.one("load",g);if(/MSIE (\d+\.\d+);/.test(navigator.userAgent)){var a=this.attr("src"),c=a.match(/\?/)?"&":"?",c=c+("random="+(new Date).getTime());
this.attr("src",a+c)}}a.attr("src")?a[0].complete||4===a[0].readyState?g():b.call(a):g()};e.matchMedia=e.matchMedia||function(a){var c,g=a.documentElement,b=g.firstElementChild||g.firstChild,d=a.createElement("body"),e=a.createElement("div");e.id="mq-test-1";e.style.cssText="position:absolute;top:-100em";d.style.background="none";d.appendChild(e);return function(a){e.innerHTML='&shy;<style media="'+a+'"> #mq-test-1 { width: 42px; }</style>';g.insertBefore(d,b);c=42===e.offsetWidth;g.removeChild(d);
return{matches:c,media:a}}}(m);(function(a){function c(){g&&(b(c),p&&jQuery.fx.tick())}var g,d=0;a=["webkit","moz"];for(var b=e.requestAnimationFrame,f=e.cancelAnimationFrame,p="undefined"!==typeof jQuery.fx;d<a.length&&!b;d++)b=e[a[d]+"RequestAnimationFrame"],f=f||e[a[d]+"CancelAnimationFrame"]||e[a[d]+"CancelRequestAnimationFrame"];b?(e.requestAnimationFrame=b,e.cancelAnimationFrame=f,p&&(jQuery.fx.timer=function(a){a()&&jQuery.timers.push(a)&&!g&&(g=!0,c())},jQuery.fx.stop=function(){g=!1})):(e.requestAnimationFrame=
function(a){var c=(new Date).getTime(),p=Math.max(0,16-(c-d)),b=e.setTimeout(function(){a(c+p)},p);d=c+p;return b},e.cancelAnimationFrame=function(a){clearTimeout(a)})})(jQuery);e.Foundation={name:"Foundation",version:"5.2.2",media_queries:{small:l(".foundation-mq-small").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,""),medium:l(".foundation-mq-medium").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,""),large:l(".foundation-mq-large").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,
""),xlarge:l(".foundation-mq-xlarge").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,""),xxlarge:l(".foundation-mq-xxlarge").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,"")},stylesheet:d("<style></style>").appendTo("head")[0].sheet,global:{namespace:f},init:function(a,c,d,b,e){d=[a,d,b,e];b=[];this.rtl=/rtl/i.test(l("html").attr("dir"));this.scope=a||this.scope;this.set_namespace();if(c&&"string"===typeof c&&!/reflow/i.test(c))this.libs.hasOwnProperty(c)&&b.push(this.init_lib(c,
d));else for(var f in this.libs)b.push(this.init_lib(f,c));return a},init_lib:function(a,c){if(this.libs.hasOwnProperty(a)){this.patch(this.libs[a]);if(c&&c.hasOwnProperty(a))return"undefined"!==typeof this.libs[a].settings?d.extend(!0,this.libs[a].settings,c[a]):"undefined"!==typeof this.libs[a].defaults&&d.extend(!0,this.libs[a].defaults,c[a]),this.libs[a].init.apply(this.libs[a],[this.scope,c[a]]);c=c instanceof Array?c:Array(c);return this.libs[a].init.apply(this.libs[a],c)}return function(){}},
patch:function(a){a.scope=this.scope;a.namespace=this.global.namespace;a.rtl=this.rtl;a.data_options=this.utils.data_options;a.attr_name=k;a.add_namespace=t;a.bindings=b;a.S=this.utils.S},inherit:function(a,c){for(var b=c.split(" "),d=b.length;d--;)this.utils.hasOwnProperty(b[d])&&(a[b[d]]=this.utils[b[d]])},set_namespace:function(){var a=this.global.namespace===f?d(".foundation-data-attribute-namespace").css("font-family"):this.global.namespace;this.global.namespace=a===f||/false/i.test(a)?"":a},
libs:{},utils:{S:l,throttle:function(a,c){var b=null;return function(){var d=this,e=arguments;null==b&&(b=setTimeout(function(){a.apply(d,e);b=null},c))}},debounce:function(a,c,b){var d,e;return function(){var f=this,p=arguments,A=b&&!d;clearTimeout(d);d=setTimeout(function(){d=null;b||(e=a.apply(f,p))},c);A&&(e=a.apply(f,p));return e}},data_options:function(a){function c(a){return!isNaN(a-0)&&null!==a&&""!==a&&!1!==a&&!0!==a}function b(a){return"string"===typeof a?d.trim(a):a}var e={},f,k;a=function(a){var c=
Foundation.global.namespace;return 0<c.length?a.data(c+"-options"):a.data("options")}(a);if("object"===typeof a)return a;k=(a||":").split(";");for(a=k.length;a--;)f=k[a].split(":"),/true/i.test(f[1])&&(f[1]=!0),/false/i.test(f[1])&&(f[1]=!1),c(f[1])&&(-1===f[1].indexOf(".")?f[1]=parseInt(f[1],10):f[1]=parseFloat(f[1])),2===f.length&&0<f[0].length&&(e[b(f[0])]=b(f[1]));return e},register_media:function(a,c){if(Foundation.media_queries[a]===f){d("head").append('<meta class="'+c+'">');var b=Foundation.media_queries,
e=d("."+c).css("font-family");if("string"===typeof e||e instanceof String)e=e.replace(/^['\\/"]+|(;\s?})+|['\\/"]+$/g,"");b[a]=e}},add_custom_rule:function(a,c){c===f?Foundation.stylesheet.insertRule(a,Foundation.stylesheet.cssRules.length):Foundation.media_queries[c]!==f&&Foundation.stylesheet.insertRule("@media "+Foundation.media_queries[c]+"{ "+a+" }")},image_loaded:function(a,c){var b=this,d=a.length;0===d&&c(a);a.each(function(){n(b.S(this),function(){--d;0===d&&c(a)})})},random_str:function(){this.fidx||
(this.fidx=0);this.prefix=this.prefix||[this.name||"F",(+new Date).toString(36)].join("-");return this.prefix+(this.fidx++).toString(36)}}};d.fn.foundation=function(){var a=Array.prototype.slice.call(arguments,0);return this.each(function(){Foundation.init.apply(Foundation,[this].concat(a));return this})}})(jQuery,this,this.document);String.prototype.rightChars=function(d){return 0>=d?"":d>this.length?this:this.substring(this.length,this.length-d)};
(function(d){var e={highlightSpeed:20,typeSpeed:75,clearDelay:500,typeDelay:200,clearOnHighlight:!1,typerDataAttr:"data-typer-targets",typerInterval:2E3,highlightColor:"#FFF",textColor:"#3868d6",initialDelay:1E3,typerOrder:"sequential"},m,f,l,k,t,b,n,a,c,g,B,q,C;k=function(a,b){"rgba(0, 0, 0, 0)"===a&&(a="rgb(255, 255, 255)");return d("<span></span>").css("color",a).css("background-color",b)};a=function(a){return!isNaN(parseFloat(a))&&isFinite(a)};n=function(a){a.removeData("typePosition highlightPosition leftStop rightStop primaryColor backgroundColor text typing".split(" "))};
l=function(a){var b=a.data("text"),c=a.data("oldLeft"),d=a.data("oldRight");b&&0!==b.length?(a.text(c+b.charAt(0)+d).data({oldLeft:c+b.charAt(0),text:b.substring(1)}),setTimeout(function(){l(a)},B())):n(a)};f=function(a){a.find("span").remove();setTimeout(function(){l(a)},b())};m=function(b){var c=b.data("highlightPosition"),d,e,l;a(c)||(c=b.data("rightStop")+1);c<=b.data("leftStop")?setTimeout(function(){f(b)},t()):(d=b.text().substring(0,c-1),e=b.text().substring(c-1,b.data("rightStop")+1),l=b.text().substring(b.data("rightStop")+
1),b.html(d).append(k(b.data("backgroundColor"),b.data("primaryColor")).append(e)).append(l),b.data("highlightPosition",c-1),setTimeout(function(){return m(b)},g()))};c=function(){var a=0;return function(b){var c;if(!b.data("typing")){try{c=JSON.parse(b.attr(d.typer.options.typerDataAttr)).targets}catch(e){}"undefined"===typeof c&&(c=d.map(b.attr(d.typer.options.typerDataAttr).split(","),function(a){return d.trim(a)}));"random"==d.typer.options.typerOrder?b.typeTo(c[Math.floor(Math.random()*c.length)]):
"sequential"==d.typer.options.typerOrder?(b.typeTo(c[a]),a=a<c.length-1?a+1:0):(console.error("Type order of '"+d.typer.options.typerOrder+"' not supported"),clearInterval(q))}}}();d.typer={options:e};d.extend(d.typer,{options:e});d.fn.typer=function(){return d(this).each(function(){var a=d(this);"undefined"!==typeof a.attr(d.typer.options.typerDataAttr)&&(c(a),q=setInterval(function(){c(a)},C()))})};d.fn.typeTo=function(a){var b=d(this),c=b.text(),e=0,f=0;if(c===a)return console.log("Our strings our equal, nothing to type"),
b;if(c!==b.html())return console.error("Typer does not work on elements with child elements."),b;for(b.data("typing",!0);c.charAt(e)===a.charAt(e);)e++;for(;c.rightChars(f)===a.rightChars(f);)f++;a=a.substring(e,a.length-f+1);b.data({oldLeft:c.substring(0,e),oldRight:c.rightChars(f-1),leftStop:e,rightStop:c.length-f,primaryColor:d.typer.options.highlightColor||b.css("color"),backgroundColor:d.typer.options.textColor||b.css("background-color"),text:a});window.setTimeout(function(){m(b);return b},d.typer.options.initialDelay)};
g=function(){return d.typer.options.highlightSpeed};B=function(){return d.typer.options.typeSpeed};t=function(){return d.typer.options.clearDelay};b=function(){return d.typer.options.typeDelay};C=function(){return d.typer.options.typerInterval}})(jQuery);/*
 HTML5 Shiv prev3.7.1 | @afarkas @jdalton @jon_neal @rem | MIT/GPL2 Licensed
*/
window.Modernizr=function(d,e,m){function f(a,b){return typeof a===b}function l(a,b){for(var d in a){var e=a[d];if(!~(""+e).indexOf("-")&&c[e]!==m)return"pfx"==b?e:!0}return!1}function k(a,b,c){var d=a.charAt(0).toUpperCase()+a.slice(1),e=(a+" "+C.join(d+" ")+d).split(" ");if(f(b,"string")||f(b,"undefined"))return l(e,b);e=(a+" "+p.join(d+" ")+d).split(" ");a:{a=e;for(var g in a)if(d=b[a[g]],d!==m){b=!1===c?a[g]:f(d,"function")?d.bind(c||b):d;break a}b=!1}return b}function t(){b.input=function(a){for(var b=
0,c=a.length;b<c;b++)y[a[b]]=!!(a[b]in g);y.list&&(y.list=!(!e.createElement("datalist")||!d.HTMLDataListElement));return y}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));b.inputtypes=function(a){for(var b=0,c,d,f=a.length;b<f;b++){g.setAttribute("type",d=a[b]);if(c="text"!==g.type)g.value=":)",g.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(d)&&g.style.WebkitAppearance!==m?(n.appendChild(g),c=e.defaultView,c=c.getComputedStyle&&
"textfield"!==c.getComputedStyle(g,null).WebkitAppearance&&0!==g.offsetHeight,n.removeChild(g)):/^(search|tel)$/.test(d)||(c=/^(url|email)$/.test(d)?g.checkValidity&&!1===g.checkValidity():":)"!=g.value);A[a[b]]=!!c}return A}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var b={},n=e.documentElement,a=e.createElement("modernizr"),c=a.style,g=e.createElement("input"),B={}.toString,q=" -webkit- -moz- -o- -ms- ".split(" "),C=["Webkit","Moz","O","ms"],
p=["webkit","moz","o","ms"],a={},A={},y={},z=[],D=z.slice,E,u=function(a,b,c,d){var f,g,h=e.createElement("div"),k=e.body,l=k||e.createElement("body");if(parseInt(c,10))for(;c--;)f=e.createElement("div"),f.id=d?d[c]:"modernizr"+(c+1),h.appendChild(f);c=['&#173;<style id="smodernizr">',a,"</style>"].join("");h.id="modernizr";(k?h:l).innerHTML+=c;l.appendChild(h);k||(l.style.background="",l.style.overflow="hidden",g=n.style.overflow,n.style.overflow="hidden",n.appendChild(l));a=b(h,a);k?h.parentNode.removeChild(h):
(l.parentNode.removeChild(l),n.style.overflow=g);return!!a},x=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,c){c=c||e.createElement(a[b]||"div");b="on"+b;var d=b in c;d||(c.setAttribute||(c=e.createElement("div")),c.setAttribute&&c.removeAttribute&&(c.setAttribute(b,""),d=f(c[b],"function"),f(c[b],"undefined")||(c[b]=m),c.removeAttribute(b)));return d}}(),G={}.hasOwnProperty,r;r=f(G,"undefined")||f(G.call,"undefined")?
function(a,b){return b in a&&f(a.constructor.prototype[b],"undefined")}:function(a,b){return G.call(a,b)};Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError;var c=D.call(arguments,1),d=function(){if(this instanceof d){var e=function(){};e.prototype=b.prototype;var e=new e,f=b.apply(e,c.concat(D.call(arguments)));return Object(f)===f?f:e}return b.apply(a,c.concat(D.call(arguments)))};return d});a.flexbox=function(){return k("flexWrap")};
a.flexboxlegacy=function(){return k("boxDirection")};a.canvas=function(){var a=e.createElement("canvas");return!(!a.getContext||!a.getContext("2d"))};a.canvastext=function(){return!(!b.canvas||!f(e.createElement("canvas").getContext("2d").fillText,"function"))};a.webgl=function(){return!!d.WebGLRenderingContext};a.touch=function(){var a;"ontouchstart"in d||d.DocumentTouch&&e instanceof DocumentTouch?a=!0:u(["@media (",q.join("touch-enabled),("),"modernizr){#modernizr{top:9px;position:absolute}}"].join(""),
function(b){a=9===b.offsetTop});return a};a.geolocation=function(){return"geolocation"in navigator};a.postmessage=function(){return!!d.postMessage};a.websqldatabase=function(){return!!d.openDatabase};a.indexedDB=function(){return!!k("indexedDB",d)};a.hashchange=function(){return x("hashchange",d)&&(e.documentMode===m||7<e.documentMode)};a.history=function(){return!(!d.history||!history.pushState)};a.draganddrop=function(){var a=e.createElement("div");return"draggable"in a||"ondragstart"in a&&"ondrop"in
a};a.websockets=function(){return"WebSocket"in d||"MozWebSocket"in d};a.rgba=function(){c.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+c.backgroundColor).indexOf("rgba")};a.hsla=function(){c.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+c.backgroundColor).indexOf("rgba")||!!~(""+c.backgroundColor).indexOf("hsla")};a.multiplebgs=function(){c.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(c.background)};a.backgroundsize=
function(){return k("backgroundSize")};a.borderimage=function(){return k("borderImage")};a.borderradius=function(){return k("borderRadius")};a.boxshadow=function(){return k("boxShadow")};a.textshadow=function(){return""===e.createElement("div").style.textShadow};a.opacity=function(){var a=q.join("opacity:.55;")+"";c.cssText=a;return/^0.55$/.test(c.opacity)};a.cssanimations=function(){return k("animationName")};a.csscolumns=function(){return k("columnCount")};a.cssgradients=function(){var a=("background-image:-webkit-gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:"+
q.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);c.cssText=a;return!!~(""+c.backgroundImage).indexOf("gradient")};a.cssreflections=function(){return k("boxReflect")};a.csstransforms=function(){return!!k("transform")};a.csstransforms3d=function(){var a=!!k("perspective");a&&"webkitPerspective"in n.style&&u("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(b,c){a=9===b.offsetLeft&&3===b.offsetHeight});return a};
a.csstransitions=function(){return k("transition")};a.fontface=function(){var a;u('@font-face {font-family:"font";src:url("https://")}',function(b,c){var d=e.getElementById("smodernizr"),d=(d=d.sheet||d.styleSheet)?d.cssRules&&d.cssRules[0]?d.cssRules[0].cssText:d.cssText||"":"";a=/src/i.test(d)&&0===d.indexOf(c.split(" ")[0])});return a};a.generatedcontent=function(){var a;u('#modernizr{font:0/0 a}#modernizr:after{content:":)";visibility:hidden;font:3px/1 a}',function(b){a=3<=b.offsetHeight});return a};
a.video=function(){var a=e.createElement("video"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(c){}return b};a.audio=function(){var a=e.createElement("audio"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,""),
b.mp3=a.canPlayType("audio/mpeg;").replace(/^no$/,""),b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,"")}catch(c){}return b};a.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(a){return!1}};a.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(a){return!1}};
a.webworkers=function(){return!!d.Worker};a.applicationcache=function(){return!!d.applicationCache};a.svg=function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};a.inlinesvg=function(){var a=e.createElement("div");a.innerHTML="<svg/>";return"http://www.w3.org/2000/svg"==(a.firstChild&&a.firstChild.namespaceURI)};a.smil=function(){return!!e.createElementNS&&/SVGAnimate/.test(B.call(e.createElementNS("http://www.w3.org/2000/svg","animate")))};a.svgclippaths=
function(){return!!e.createElementNS&&/SVGClipPath/.test(B.call(e.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var h in a)r(a,h)&&(E=h.toLowerCase(),b[E]=a[h](),z.push((b[E]?"":"no-")+E));b.input||t();b.addTest=function(a,c){if("object"==typeof a)for(var d in a)r(a,d)&&b.addTest(d,a[d]);else{a=a.toLowerCase();if(b[a]!==m)return b;c="function"==typeof c?c():c;n.className+=" "+(c?"":"no-")+a;b[a]=c}return b};c.cssText="";a=g=null;(function(a,b){function c(){var a=r.elements;return"string"==
typeof a?a.split(" "):a}function d(a){var b=n[a._html5shiv];b||(b={},p++,a._html5shiv=p,n[p]=b);return b}function e(a,c,f){c||(c=b);if(q)return c.createElement(a);f||(f=d(c));c=f.cache[a]?f.cache[a].cloneNode():k.test(a)?(f.cache[a]=f.createElem(a)).cloneNode():f.createElem(a);return!c.canHaveChildren||l.test(a)||c.tagUrn?c:f.frag.appendChild(c)}function f(a,b){b.cache||(b.cache={},b.createElem=a.createElement,b.createFrag=a.createDocumentFragment,b.frag=b.createFrag());a.createElement=function(c){return r.shivMethods?
e(c,a,b):b.createElem(c)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+c().join().replace(/[\w\-]+/g,function(a){b.createElem(a);b.frag.createElement(a);return'c("'+a+'")'})+");return n}")(r,b.frag)}function g(a){a||(a=b);var c=d(a);if(r.shivCSS&&!m&&!c.hasCSS){var e,h=a;e=h.createElement("p");h=h.getElementsByTagName("head")[0]||h.documentElement;e.innerHTML="x<style>article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}template{display:none}</style>";
e=h.insertBefore(e.lastChild,h.firstChild);c.hasCSS=!!e}q||f(a,c);return a}var h=a.html5||{},l=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,k=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,m,p=0,n={},q;(function(){try{var a=b.createElement("a");a.innerHTML="<xyz></xyz>";m="hidden"in a;var c;if(!(c=1==a.childNodes.length)){b.createElement("a");var d=b.createDocumentFragment();c="undefined"==typeof d.cloneNode||"undefined"==
typeof d.createDocumentFragment||"undefined"==typeof d.createElement}q=c}catch(e){q=m=!0}})();var r={elements:h.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output progress section summary template time video",version:"3.7.0",shivCSS:!1!==h.shivCSS,supportsUnknownElements:q,shivMethods:!1!==h.shivMethods,type:"default",shivDocument:g,createElement:e,createDocumentFragment:function(a,e){a||(a=b);if(q)return a.createDocumentFragment();
e=e||d(a);for(var f=e.frag.cloneNode(),g=0,h=c(),l=h.length;g<l;g++)f.createElement(h[g]);return f}};a.html5=r;g(b)})(this,e);b._version="2.8.1";b._prefixes=q;b._domPrefixes=p;b._cssomPrefixes=C;b.mq=function(a){var b=d.matchMedia||d.msMatchMedia;if(b)return b(a)&&b(a).matches||!1;var c;u("@media "+a+" { #modernizr { position: absolute; } }",function(a){c="absolute"==(d.getComputedStyle?getComputedStyle(a,null):a.currentStyle).position});return c};b.hasEvent=x;b.testProp=function(a){return l([a])};
b.testAllProps=k;b.testStyles=u;b.prefixed=function(a,b,c){return b?k(a,b,c):k(a,"pfx")};n.className=n.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+z.join(" "));return b}(this,this.document);(function(){var d,e,m,f,l,k,t,b,n,a,c,g,B,q,C,p,A,y,z,D,E,u,x,G,r,h,K,O,T,H,P,L,w,F,Q,J,N,S,M,V,R,Y,U,I=[].slice,W={}.hasOwnProperty,X=function(a,b){function c(){this.constructor=a}for(var d in b)W.call(b,d)&&(a[d]=b[d]);c.prototype=b.prototype;a.prototype=new c;a.__super__=b.prototype;return a},Z=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in this&&this[b]===a)return b;return-1};m={catchupTime:100,initialRate:.03,minTime:250,ghostTime:100,maxProgressPerFrame:20,easeFactor:1.25,
startOnPageLoad:!1,restartOnPushState:!0,restartOnRequestAfter:500,target:"body",elements:{checkInterval:100,selectors:["body"]},eventLag:{minSamples:10,sampleCount:3,lagThreshold:3},ajax:{trackMethods:["GET"],trackWebSockets:!0,ignoreURLs:[]}};r=function(){var a;return null!=(a="undefined"!==typeof performance&&null!==performance?"function"===typeof performance.now?performance.now():void 0:void 0)?a:+new Date};K=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;y=window.cancelAnimationFrame||window.mozCancelAnimationFrame;null==K&&(K=function(a){return setTimeout(a,50)},y=function(a){return clearTimeout(a)});T=function(a){var b,c;b=r();c=function(){var d;d=r()-b;return 33<=d?(b=r(),a(d,function(){return K(c)})):setTimeout(c,33-d)};return c()};O=function(){var a,b,c;c=arguments[0];b=arguments[1];a=3<=arguments.length?I.call(arguments,2):[];return"function"===typeof c[b]?c[b].apply(c,a):c[b]};z=function(){var a,b,c,d,e,f,g;b=
arguments[0];d=2<=arguments.length?I.call(arguments,1):[];f=0;for(g=d.length;f<g;f++)if(c=d[f])for(a in c)W.call(c,a)&&(e=c[a],null!=b[a]&&"object"===typeof b[a]&&null!=e&&"object"===typeof e?z(b[a],e):b[a]=e);return b};C=function(a){var b,c,d,e,f;e=c=b=0;for(f=a.length;e<f;e++)d=a[e],c+=Math.abs(d),b++;return c/b};f=function(){function a(){}a.prototype.on=function(a,b,c,d){var e;null==d&&(d=!1);null==this.bindings&&(this.bindings={});null==(e=this.bindings)[a]&&(e[a]=[]);return this.bindings[a].push({handler:b,
ctx:c,once:d})};a.prototype.once=function(a,b,c){return this.on(a,b,c,!0)};a.prototype.off=function(a,b){var c,d;if(null!=(null!=(c=this.bindings)?c[a]:void 0)){if(null==b)return delete this.bindings[a];c=0;for(d=[];c<this.bindings[a].length;)this.bindings[a][c].handler===b?d.push(this.bindings[a].splice(c,1)):d.push(c++);return d}};a.prototype.trigger=function(){var a,b,c,d,e,v,f;c=arguments[0];a=2<=arguments.length?I.call(arguments,1):[];if(null!=(b=this.bindings)&&b[c]){e=0;for(f=[];e<this.bindings[c].length;)v=
this.bindings[c][e],d=v.handler,b=v.ctx,v=v.once,d.apply(null!=b?b:this,a),v?f.push(this.bindings[c].splice(e,1)):f.push(e++);return f}};return a}();b=window.Pace||{};window.Pace=b;z(b,f.prototype);h=b.options=z({},m,window.paceOptions,function(a,b){var c;null==a&&(a="options");null==b&&(b=!0);if(c=document.querySelector("[data-pace-"+a+"]")){c=c.getAttribute("data-pace-"+a);if(!b)return c;try{return JSON.parse(c)}catch(d){return"undefined"!==typeof console&&null!==console?console.error("Error parsing inline pace options",
d):void 0}}}());R=["ajax","document","eventLag","elements"];f=0;for(k=R.length;f<k;f++)w=R[f],!0===h[w]&&(h[w]=m[w]);t=function(a){function b(){return Y=b.__super__.constructor.apply(this,arguments)}X(b,a);return b}(Error);e=function(){function a(){this.progress=0}a.prototype.getElement=function(){var a;if(null==this.el){a=document.querySelector(h.target);if(!a)throw new t;this.el=document.createElement("div");this.el.className="pace pace-active";document.body.className=document.body.className.replace(/pace-done/g,
"");document.body.className+=" pace-running";this.el.innerHTML='<div class="pace-progress">\n  <div class="pace-progress-inner"></div>\n</div>\n<div class="pace-activity"></div>';null!=a.firstChild?a.insertBefore(this.el,a.firstChild):a.appendChild(this.el)}return this.el};a.prototype.finish=function(){var a;a=this.getElement();a.className=a.className.replace("pace-active","");a.className+=" pace-inactive";document.body.className=document.body.className.replace("pace-running","");return document.body.className+=
" pace-done"};a.prototype.update=function(a){this.progress=a;return this.render()};a.prototype.destroy=function(){try{this.getElement().parentNode.removeChild(this.getElement())}catch(a){t=a}return this.el=void 0};a.prototype.render=function(){var a,b,c,d,e,f;if(null==document.querySelector(h.target))return!1;a=this.getElement();c="translate3d(100%, "+(100-this.progress)+"%, 0)";f=["webkitTransform","msTransform","transform"];d=0;for(e=f.length;d<e;d++)b=f[d],a.children[0].style[b]=c;if(!this.lastRenderedProgress||
this.lastRenderedProgress|0!==this.progress|0)a.children[0].setAttribute("data-progress-text",""+(this.progress|0)+"%"),100<=this.progress?b="99":(b=10>this.progress?"0":"",b+=this.progress|0),a.children[0].setAttribute("data-progress",""+b);return this.lastRenderedProgress=this.progress};a.prototype.done=function(){return 100<=this.progress};return a}();m=function(){function a(){this.bindings={}}a.prototype.trigger=function(a,b){var c,d,e,f,v;if(null!=this.bindings[a]){f=this.bindings[a];v=[];d=
0;for(e=f.length;d<e;d++)c=f[d],v.push(c.call(this,b));return v}};a.prototype.on=function(a,b){var c;null==(c=this.bindings)[a]&&(c[a]=[]);return this.bindings[a].push(b)};return a}();S=window.XMLHttpRequest;N=window.XDomainRequest;J=window.WebSocket;D=function(a,b){var c,d;d=[];for(c in b.prototype)try{null==a[c]&&"function"!==typeof b[c]?"function"===typeof Object.defineProperty?d.push(Object.defineProperty(a,c,{get:function(){return b.prototype[c]},configurable:!0,enumerable:!0})):d.push(a[c]=
b.prototype[c]):d.push(void 0)}catch(e){}return d};x=[];b.ignore=function(){var a,b;b=arguments[0];a=2<=arguments.length?I.call(arguments,1):[];x.unshift("ignore");a=b.apply(null,a);x.shift();return a};b.track=function(){var a,b;b=arguments[0];a=2<=arguments.length?I.call(arguments,1):[];x.unshift("track");a=b.apply(null,a);x.shift();return a};L=function(a){var b;null==a&&(a="GET");return"track"===x[0]?"force":!x.length&&h.ajax&&("socket"===a&&h.ajax.trackWebSockets||(b=a.toUpperCase(),0<=Z.call(h.ajax.trackMethods,
b)))?!0:!1};n=function(a){function b(){var a,c=this;b.__super__.constructor.apply(this,arguments);a=function(a){var b;b=a.open;return a.open=function(d,e,f){L(d)&&c.trigger("request",{type:d,url:e,request:a});return b.apply(a,arguments)}};window.XMLHttpRequest=function(b){b=new S(b);a(b);return b};try{D(window.XMLHttpRequest,S)}catch(d){}if(null!=N){window.XDomainRequest=function(){var b;b=new N;a(b);return b};try{D(window.XDomainRequest,N)}catch(d){}}if(null!=J&&h.ajax.trackWebSockets){window.WebSocket=
function(a,b){var d;d=null!=b?new J(a,b):new J(a);L("socket")&&c.trigger("request",{type:"socket",url:a,protocols:b,request:d});return d};try{D(window.WebSocket,J)}catch(d){}}}X(b,a);return b}(m);M=null;E=function(){null==M&&(M=new n);return M};P=function(a){var b,c,d,e;e=h.ajax.ignoreURLs;c=0;for(d=e.length;c<d;c++)if(b=e[c],"string"===typeof b){if(-1!==a.indexOf(b))return!0}else if(b.test(a))return!0;return!1};E().on("request",function(a){var c,e,f,g;g=a.type;f=a.request;if(!(P(a.url)||b.running||
!1===h.restartOnRequestAfter&&"force"!==L(g)))return e=arguments,c=h.restartOnRequestAfter||0,"boolean"===typeof c&&(c=0),setTimeout(function(){var a,c,v,h;if("socket"===g?2>f.readyState:0<(a=f.readyState)&&4>a){b.restart();v=b.sources;h=[];a=0;for(c=v.length;a<c;a++)if(w=v[a],w instanceof d){w.watch.apply(w,e);break}else h.push(void 0);return h}},c)});d=function(){function a(){var b=this;this.elements=[];E().on("request",function(){return b.watch.apply(b,arguments)})}a.prototype.watch=function(a){var b,
c;c=a.type;b=a.request;if(!P(a.url))return a="socket"===c?new g(b):new B(b),this.elements.push(a)};return a}();B=function(){return function(a){var b,c,d,e,f,g=this;this.progress=0;if(null!=window.ProgressEvent)for(a.addEventListener("progress",function(a){return a.lengthComputable?g.progress=100*a.loaded/a.total:g.progress+=(100-g.progress)/2},!1),f=["load","abort","timeout","error"],c=0,d=f.length;c<d;c++)b=f[c],a.addEventListener(b,function(){return g.progress=100},!1);else e=a.onreadystatechange,
a.onreadystatechange=function(){var b;0===(b=a.readyState)||4===b?g.progress=100:3===a.readyState&&(g.progress=50);return"function"===typeof e?e.apply(null,arguments):void 0}}}();g=function(){return function(a){var b,c,d,e,f=this;this.progress=0;e=["error","open"];c=0;for(d=e.length;c<d;c++)b=e[c],a.addEventListener(b,function(){return f.progress=100},!1)}}();f=function(){return function(a){var b,c,d;null==a&&(a={});this.elements=[];null==a.selectors&&(a.selectors=[]);d=a.selectors;b=0;for(c=d.length;b<
c;b++)a=d[b],this.elements.push(new l(a))}}();l=function(){function a(b){this.selector=b;this.progress=0;this.check()}a.prototype.check=function(){var a=this;return document.querySelector(this.selector)?this.done():setTimeout(function(){return a.check()},h.elements.checkInterval)};a.prototype.done=function(){return this.progress=100};return a}();m=function(){function a(){var b,c,d=this;this.progress=null!=(c=this.states[document.readyState])?c:100;b=document.onreadystatechange;document.onreadystatechange=
function(){null!=d.states[document.readyState]&&(d.progress=d.states[document.readyState]);return"function"===typeof b?b.apply(null,arguments):void 0}}a.prototype.states={loading:0,interactive:50,complete:100};return a}();k=function(){return function(){var a,b,c,d,e,f=this;a=this.progress=0;e=[];d=0;c=r();b=setInterval(function(){var g;g=r()-c-50;c=r();e.push(g);e.length>h.eventLag.sampleCount&&e.shift();a=C(e);return++d>=h.eventLag.minSamples&&a<h.eventLag.lagThreshold?(f.progress=100,clearInterval(b)):
f.progress=3/(a+3)*100},50)}}();c=function(){function a(b){this.source=b;this.last=this.sinceLastUpdate=0;this.rate=h.initialRate;this.progress=this.lastProgress=this.catchup=0;null!=this.source&&(this.progress=O(this.source,"progress"))}a.prototype.tick=function(a,b){null==b&&(b=O(this.source,"progress"));100<=b&&(this.done=!0);b===this.last?this.sinceLastUpdate+=a:(this.sinceLastUpdate&&(this.rate=(b-this.last)/this.sinceLastUpdate),this.catchup=(b-this.progress)/h.catchupTime,this.sinceLastUpdate=
0,this.last=b);b>this.progress&&(this.progress+=this.catchup*a);this.progress+=(1-Math.pow(this.progress/100,h.easeFactor))*this.rate*a;this.progress=Math.min(this.lastProgress+h.maxProgressPerFrame,this.progress);this.progress=Math.max(0,this.progress);return this.lastProgress=this.progress=Math.min(100,this.progress)};return a}();A=q=Q=p=H=F=null;b.running=!1;u=function(){if(h.restartOnPushState)return b.restart()};null!=window.history.pushState&&(V=window.history.pushState,window.history.pushState=
function(){u();return V.apply(window.history,arguments)});null!=window.history.replaceState&&(U=window.history.replaceState,window.history.replaceState=function(){u();return U.apply(window.history,arguments)});a={ajax:d,elements:f,document:m,eventLag:k};(G=function(){var d,f,g,l,k;b.sources=F=[];k=["ajax","elements","document","eventLag"];f=0;for(l=k.length;f<l;f++)d=k[f],!1!==h[d]&&F.push(new a[d](h[d]));d=null!=(g=h.extraSources)?g:[];g=0;for(f=d.length;g<f;g++)w=d[g],F.push(new w(h));b.bar=p=new e;
H=[];return Q=new c})();b.stop=function(){b.trigger("stop");b.running=!1;p.destroy();A=!0;null!=q&&("function"===typeof y&&y(q),q=null);return G()};b.restart=function(){b.trigger("restart");b.stop();return b.start()};b.go=function(){var a;b.running=!0;p.render();a=r();A=!1;return q=T(function(d,e){var f,g,l,k,m,n,q,t,u,x,y,z;f=q=0;g=!0;k=t=0;for(x=F.length;t<x;k=++t)for(w=F[k],n=null!=H[k]?H[k]:H[k]=[],k=null!=(z=w.elements)?z:[w],m=u=0,y=k.length;u<y;m=++u)l=k[m],l=null!=n[m]?n[m]:n[m]=new c(l),
g&=l.done,l.done||(f++,q+=l.tick(d));p.update(Q.tick(d,q/f));return p.done()||g||A?(p.update(100),b.trigger("done"),setTimeout(function(){b.running=!1;return b.trigger("hide")},Math.max(h.ghostTime,Math.max(h.minTime-(r()-a),0)))):e()})};b.start=function(a){z(h,a);b.running=!0;try{p.render()}catch(c){t=c}return document.querySelector(".pace")?(b.trigger("start"),b.go()):setTimeout(b.start,50)};"function"===typeof define&&define.amd?define(["pace"],function(){return b}):"object"===typeof exports?module.exports=
b:h.startOnPageLoad&&b.start();$.fn.imagesLoaded=function(){var a=this.find('img[src!=""]');if(!a.length)return $.Deferred().resolve().promise();var b=[];a.each(function(){var a=$.Deferred();b.push(a);var c=new Image;c.onload=function(){a.resolve()};c.onerror=function(){a.resolve()};c.src=this.src});return $.when.apply($,b)};$(function(){$("[data-typer-targets]").typer();$("#hello .link").click(function(){$("#about").addClass("open");$("#hello").addClass("noScroll");$("html, body").animate({scrollTop:$("#about").offset().top},
1E3);$(".close-about").click(function(){$("#about").removeClass("open");$("#hello").removeClass("noScroll")})});var a,c=0,d,e=0,f=$("body"),g=!0,h=$(".back-row .close-top");$(".thumb").scroll(function(){a=!0});setInterval(function(){if(a&&g){var b=d.offset().top-$(window).scrollTop();b>c?(b>=-0+$(".close-top").outerHeight()&&$(".x").removeClass("dark"),d.find(".back.close-bottom").offset().top>$(".thumb.open").offset().top+$(window).height()&&($(".back-row").addClass("loaded"),$(".pace-inactive").removeClass("pace-hidden"))):
d.find(".back.close-bottom").offset().top<=$(".thumb.open").offset().top+$(window).height()?($(".back-row").removeClass("loaded"),$(".pace-inactive").addClass("pace-hidden")):b<-0+$(".close-top").outerHeight()&&$(".x").addClass("dark");c=b;a=!1}},250);h.click(function(){g=!1;var a=$(".thumb.open"),b=$(".thumb.open .story");$(".back-row").removeClass("loaded");console.log($(window).scrollTop()-b.offset().top);a.animate({scrollTop:0},700);$(".story.open .intro").removeClass("loaded");$(".intro").removeClass("loaded");
$(".pace-inactive").addClass("pace-hidden");setTimeout(function(){a.removeClass("open").addClass("closed").removeAttr("style");b.removeClass("open");f.removeClass("noScroll").removeAttr("style").scrollTop(-e);setTimeout(function(){b.html("")},200)},1E3)});$(".thumb").click(function(a){var c=$(this),h=c.data("project"),k=c.find(".story"),l=""+h+".php";$(a.target).hasClass("close-bottom")?(g=!1,k.animate({marginTop:-k.height()},700),setTimeout(function(){k.html("");c.removeAttr("style").removeClass("open").addClass("closed");
f.removeClass("noScroll").removeAttr("style").scrollTop(-e)},1E3)):$(".thumb").hasClass("open")||($windowTop=$(window).scrollTop(),c.addClass("open").addClass("loading").removeClass("closed"),e=-$windowTop,$(".thumb.open").css("top",$windowTop),k.removeAttr("style"),k.addClass("open"),f.addClass("noScroll"),f.css("top",e),d=$(".thumb.open").find(".story"),setTimeout(function(){b.restart();$(".close-top").removeClass("dark");$.ajax({url:l,success:function(a){k.html(a);$(d).html(a).imagesLoaded().then(function(){setTimeout(function(){g=
!0;p.finish();$(".back-row").addClass("loaded");c.find(".intro").first().addClass("loaded");c.removeClass("loading")},1200)})}})},1E3))})})}).call(this);