(function(){var K,T,p,m,U,B,C,k,V,W,L,X,Y,u,Z,r,D,E,v,F,M,N,q,aa,t,h,G,O,ba,z,P,H,n,y,Q,w,I,R,J,ca,S,ga,da,A=[].slice,ea={}.hasOwnProperty,fa=function(a,b){function d(){this.constructor=a}for(var c in b)ea.call(b,c)&&(a[c]=b[c]);d.prototype=b.prototype;a.prototype=new d;a.__super__=b.prototype;return a},ha=[].indexOf||function(a){for(var b=0,d=this.length;b<d;b++)if(b in this&&this[b]===a)return b;return-1};p={catchupTime:100,initialRate:.03,minTime:250,ghostTime:100,maxProgressPerFrame:20,easeFactor:1.25,
startOnPageLoad:!1,restartOnPushState:!0,restartOnRequestAfter:500,target:"body",elements:{checkInterval:100,selectors:["body"]},eventLag:{minSamples:10,sampleCount:3,lagThreshold:3},ajax:{trackMethods:["GET"],trackWebSockets:!0,ignoreURLs:[]}};t=function(){var a;return null!=(a="undefined"!==typeof performance&&null!==performance?"function"===typeof performance.now?performance.now():void 0:void 0)?a:+new Date};G=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;E=window.cancelAnimationFrame||window.mozCancelAnimationFrame;null==G&&(G=function(a){return setTimeout(a,50)},E=function(a){return clearTimeout(a)});ba=function(a){var b,d;b=t();d=function(){var c;c=t()-b;return 33<=c?(b=t(),a(c,function(){return G(d)})):setTimeout(d,33-c)};return d()};O=function(){var a,b,d;d=arguments[0];b=arguments[1];a=3<=arguments.length?A.call(arguments,2):[];return"function"===typeof d[b]?d[b].apply(d,a):d[b]};v=function(){var a,b,d,c,e,g,f;
b=arguments[0];c=2<=arguments.length?A.call(arguments,1):[];g=0;for(f=c.length;g<f;g++)if(d=c[g])for(a in d)ea.call(d,a)&&(e=d[a],null!=b[a]&&"object"===typeof b[a]&&null!=e&&"object"===typeof e?v(b[a],e):b[a]=e);return b};Z=function(a){var b,d,c,e,g;e=d=b=0;for(g=a.length;e<g;e++)c=a[e],d+=Math.abs(c),b++;return d/b};m=function(){function a(){}a.prototype.on=function(b,a,c,e){var g;null==e&&(e=!1);null==this.bindings&&(this.bindings={});null==(g=this.bindings)[b]&&(g[b]=[]);return this.bindings[b].push({handler:a,
ctx:c,once:e})};a.prototype.once=function(b,a,c){return this.on(b,a,c,!0)};a.prototype.off=function(b,a){var c,e;if(null!=(null!=(c=this.bindings)?c[b]:void 0)){if(null==a)return delete this.bindings[b];c=0;for(e=[];c<this.bindings[b].length;)this.bindings[b][c].handler===a?e.push(this.bindings[b].splice(c,1)):e.push(c++);return e}};a.prototype.trigger=function(){var b,a,c,e,g,f,l;c=arguments[0];b=2<=arguments.length?A.call(arguments,1):[];if(null!=(a=this.bindings)&&a[c]){g=0;for(l=[];g<this.bindings[c].length;)f=
this.bindings[c][g],e=f.handler,a=f.ctx,f=f.once,e.apply(null!=a?a:this,b),f?l.push(this.bindings[c].splice(g,1)):l.push(g++);return l}};return a}();k=window.Pace||{};window.Pace=k;v(k,m.prototype);h=k.options=v({},p,window.paceOptions,function(a,b){var d;null==a&&(a="options");null==b&&(b=!0);if(d=document.querySelector("[data-pace-"+a+"]")){d=d.getAttribute("data-pace-"+a);if(!b)return d;try{return JSON.parse(d)}catch(c){return"undefined"!==typeof console&&null!==console?console.error("Error parsing inline pace options",
c):void 0}}}());S=["ajax","document","eventLag","elements"];m=0;for(B=S.length;m<B;m++)n=S[m],!0===h[n]&&(h[n]=p[n]);C=function(a){function b(){return ga=b.__super__.constructor.apply(this,arguments)}fa(b,a);return b}(Error);T=function(){function a(){this.progress=0}a.prototype.getElement=function(){var b;if(null==this.el){b=document.querySelector(h.target);if(!b)throw new C;this.el=document.createElement("div");this.el.className="pace pace-active";document.body.className=document.body.className.replace(/pace-done/g,
"");document.body.className+=" pace-running";this.el.innerHTML='<div class="pace-progress">\n  <div class="pace-progress-inner"></div>\n</div>\n<div class="pace-activity"></div>';null!=b.firstChild?b.insertBefore(this.el,b.firstChild):b.appendChild(this.el)}return this.el};a.prototype.finish=function(){var b;b=this.getElement();b.className=b.className.replace("pace-active","");b.className+=" pace-inactive";document.body.className=document.body.className.replace("pace-running","");return document.body.className+=
" pace-done"};a.prototype.update=function(b){this.progress=b;return this.render()};a.prototype.destroy=function(){try{this.getElement().parentNode.removeChild(this.getElement())}catch(b){C=b}return this.el=void 0};a.prototype.render=function(){var b,a,c,e,g,f;if(null==document.querySelector(h.target))return!1;b=this.getElement();c="translate3d(100%, "+(100-this.progress)+"%, 0)";f=["webkitTransform","msTransform","transform"];e=0;for(g=f.length;e<g;e++)a=f[e],b.children[0].style[a]=c;if(!this.lastRenderedProgress||
this.lastRenderedProgress|0!==this.progress|0)b.children[0].setAttribute("data-progress-text",""+(this.progress|0)+"%"),100<=this.progress?a="99":(a=10>this.progress?"0":"",a+=this.progress|0),b.children[0].setAttribute("data-progress",""+a);return this.lastRenderedProgress=this.progress};a.prototype.done=function(){return 100<=this.progress};return a}();p=function(){function a(){this.bindings={}}a.prototype.trigger=function(b,a){var c,e,g,f,l;if(null!=this.bindings[b]){f=this.bindings[b];l=[];e=
0;for(g=f.length;e<g;e++)c=f[e],l.push(c.call(this,a));return l}};a.prototype.on=function(b,a){var c;null==(c=this.bindings)[b]&&(c[b]=[]);return this.bindings[b].push(a)};return a}();R=window.XMLHttpRequest;I=window.XDomainRequest;w=window.WebSocket;F=function(a,b){var d,c;c=[];for(d in b.prototype)try{null==a[d]&&"function"!==typeof b[d]?"function"===typeof Object.defineProperty?c.push(Object.defineProperty(a,d,{get:function(){return b.prototype[d]},configurable:!0,enumerable:!0})):c.push(a[d]=
b.prototype[d]):c.push(void 0)}catch(e){}return c};q=[];k.ignore=function(){var a,b;b=arguments[0];a=2<=arguments.length?A.call(arguments,1):[];q.unshift("ignore");a=b.apply(null,a);q.shift();return a};k.track=function(){var a,b;b=arguments[0];a=2<=arguments.length?A.call(arguments,1):[];q.unshift("track");a=b.apply(null,a);q.shift();return a};H=function(a){var b;null==a&&(a="GET");return"track"===q[0]?"force":!q.length&&h.ajax&&("socket"===a&&h.ajax.trackWebSockets||(b=a.toUpperCase(),0<=ha.call(h.ajax.trackMethods,
b)))?!0:!1};V=function(a){function b(){var a,c=this;b.__super__.constructor.apply(this,arguments);a=function(a){var b;b=a.open;return a.open=function(d,e,k){H(d)&&c.trigger("request",{type:d,url:e,request:a});return b.apply(a,arguments)}};window.XMLHttpRequest=function(b){b=new R(b);a(b);return b};try{F(window.XMLHttpRequest,R)}catch(e){}if(null!=I){window.XDomainRequest=function(){var b;b=new I;a(b);return b};try{F(window.XDomainRequest,I)}catch(e){}}if(null!=w&&h.ajax.trackWebSockets){window.WebSocket=
function(b,a){var d;d=null!=a?new w(b,a):new w(b);H("socket")&&c.trigger("request",{type:"socket",url:b,protocols:a,request:d});return d};try{F(window.WebSocket,w)}catch(e){}}}fa(b,a);return b}(p);J=null;M=function(){null==J&&(J=new V);return J};P=function(a){var b,d,c,e;e=h.ajax.ignoreURLs;d=0;for(c=e.length;d<c;d++)if(b=e[d],"string"===typeof b){if(-1!==a.indexOf(b))return!0}else if(b.test(a))return!0;return!1};M().on("request",function(a){var b,d,c,e;e=a.type;c=a.request;if(!(P(a.url)||k.running||
!1===h.restartOnRequestAfter&&"force"!==H(e)))return d=arguments,b=h.restartOnRequestAfter||0,"boolean"===typeof b&&(b=0),setTimeout(function(){var b,a,h,x;if("socket"===e?2>c.readyState:0<(b=c.readyState)&&4>b){k.restart();h=k.sources;x=[];b=0;for(a=h.length;b<a;b++)if(n=h[b],n instanceof K){n.watch.apply(n,d);break}else x.push(void 0);return x}},b)});K=function(){function a(){var b=this;this.elements=[];M().on("request",function(){return b.watch.apply(b,arguments)})}a.prototype.watch=function(b){var a,
c;c=b.type;a=b.request;if(!P(b.url))return b="socket"===c?new X(a):new Y(a),this.elements.push(b)};return a}();Y=function(){return function(a){var b,d,c,e,g,f=this;this.progress=0;if(null!=window.ProgressEvent)for(a.addEventListener("progress",function(b){return b.lengthComputable?f.progress=100*b.loaded/b.total:f.progress+=(100-f.progress)/2},!1),g=["load","abort","timeout","error"],d=0,c=g.length;d<c;d++)b=g[d],a.addEventListener(b,function(){return f.progress=100},!1);else e=a.onreadystatechange,
a.onreadystatechange=function(){var b;0===(b=a.readyState)||4===b?f.progress=100:3===a.readyState&&(f.progress=50);return"function"===typeof e?e.apply(null,arguments):void 0}}}();X=function(){return function(a){var b,d,c,e,g=this;this.progress=0;e=["error","open"];d=0;for(c=e.length;d<c;d++)b=e[d],a.addEventListener(b,function(){return g.progress=100},!1)}}();m=function(){return function(a){var b,d,c;null==a&&(a={});this.elements=[];null==a.selectors&&(a.selectors=[]);c=a.selectors;b=0;for(d=c.length;b<
d;b++)a=c[b],this.elements.push(new U(a))}}();U=function(){function a(b){this.selector=b;this.progress=0;this.check()}a.prototype.check=function(){var b=this;return document.querySelector(this.selector)?this.done():setTimeout(function(){return b.check()},h.elements.checkInterval)};a.prototype.done=function(){return this.progress=100};return a}();p=function(){function a(){var b,a,c=this;this.progress=null!=(a=this.states[document.readyState])?a:100;b=document.onreadystatechange;document.onreadystatechange=
function(){null!=c.states[document.readyState]&&(c.progress=c.states[document.readyState]);return"function"===typeof b?b.apply(null,arguments):void 0}}a.prototype.states={loading:0,interactive:50,complete:100};return a}();B=function(){return function(){var a,b,d,c,e,g=this;a=this.progress=0;e=[];c=0;d=t();b=setInterval(function(){var f;f=t()-d-50;d=t();e.push(f);e.length>h.eventLag.sampleCount&&e.shift();a=Z(e);return++c>=h.eventLag.minSamples&&a<h.eventLag.lagThreshold?(g.progress=100,clearInterval(b)):
g.progress=3/(a+3)*100},50)}}();L=function(){function a(b){this.source=b;this.last=this.sinceLastUpdate=0;this.rate=h.initialRate;this.progress=this.lastProgress=this.catchup=0;null!=this.source&&(this.progress=O(this.source,"progress"))}a.prototype.tick=function(b,a){var c;null==a&&(a=O(this.source,"progress"));100<=a&&(this.done=!0);a===this.last?this.sinceLastUpdate+=b:(this.sinceLastUpdate&&(this.rate=(a-this.last)/this.sinceLastUpdate),this.catchup=(a-this.progress)/h.catchupTime,this.sinceLastUpdate=
0,this.last=a);a>this.progress&&(this.progress+=this.catchup*b);c=1-Math.pow(this.progress/100,h.easeFactor);this.progress+=c*this.rate*b;this.progress=Math.min(this.lastProgress+h.maxProgressPerFrame,this.progress);this.progress=Math.max(0,this.progress);return this.lastProgress=this.progress=Math.min(100,this.progress)};return a}();D=u=Q=r=z=y=null;k.running=!1;N=function(){if(h.restartOnPushState)return k.restart()};null!=window.history.pushState&&(ca=window.history.pushState,window.history.pushState=
function(){N();return ca.apply(window.history,arguments)});null!=window.history.replaceState&&(da=window.history.replaceState,window.history.replaceState=function(){N();return da.apply(window.history,arguments)});W={ajax:K,elements:m,document:p,eventLag:B};(aa=function(){var a,b,d,c,e;k.sources=y=[];e=["ajax","elements","document","eventLag"];b=0;for(c=e.length;b<c;b++)a=e[b],!1!==h[a]&&y.push(new W[a](h[a]));a=null!=(d=h.extraSources)?d:[];d=0;for(b=a.length;d<b;d++)n=a[d],y.push(new n(h));k.bar=
r=new T;z=[];return Q=new L})();k.stop=function(){k.trigger("stop");k.running=!1;r.destroy();D=!0;null!=u&&("function"===typeof E&&E(u),u=null);return aa()};k.restart=function(){k.trigger("restart");k.stop();return k.start()};k.go=function(){var a;k.running=!0;r.render();a=t();D=!1;return u=ba(function(b,d){var c,e,g,f,l,x,m,p,q,u,v,w;c=m=0;e=!0;f=p=0;for(u=y.length;p<u;f=++p)for(n=y[f],x=null!=z[f]?z[f]:z[f]=[],f=null!=(w=n.elements)?w:[n],l=q=0,v=f.length;q<v;l=++q)g=f[l],g=null!=x[l]?x[l]:x[l]=
new L(g),e&=g.done,g.done||(c++,m+=g.tick(b));r.update(Q.tick(b,m/c));return r.done()||e||D?(r.update(100),k.trigger("done"),setTimeout(function(){k.running=!1;return k.trigger("hide")},Math.max(h.ghostTime,Math.max(h.minTime-(t()-a),0)))):d()})};k.start=function(a){v(h,a);k.running=!0;try{r.render()}catch(b){C=b}return document.querySelector(".pace")?(k.trigger("start"),k.go()):setTimeout(k.start,50)};"function"===typeof define&&define.amd?define(["pace"],function(){return k}):"object"===typeof exports?
module.exports=k:h.startOnPageLoad&&k.start();$resizeErrythang=function(){$windowHeight=$(window).height();$windowHeight95=.95*$windowHeight;$windowWidth=$(window).width();$ratio=$windowHeight/$windowWidth;$thumbHeight=300;switch($("#size-detector").css("background-color")){case "rgb(255, 0, 0)":$(".closed").css("height","300px");$(".story").css("marginTop",0);$(".closed.first").css("top",$windowHeight95);$(".closed.second").css("top",$windowHeight95+300);$(".closed.third").css("top",$windowHeight95+
600);$(".closed.fourth").css("top",$windowHeight95+900);$(".closed.fifth").css("top",$windowHeight95+1200);$(".closed.sixth").css("top",$windowHeight95+1500);break;case "rgb(255, 165, 0)":$(".closed").css("height",$windowWidth/2*$ratio);$(".closed.first, .closed.second").css("top",$windowHeight95);$(".closed.third, .closed.fourth").css("top",$windowHeight95+$windowWidth/2*$ratio);$(".closed.fifth, .closed.sixth").css("top",$windowHeight95+$windowWidth/2*$ratio*2);break;case "rgb(255, 255, 0)":$(".closed").css("height",
$windowWidth/3*$ratio),$(".closed.first, .closed.second, .closed.third").css("top",$windowHeight95),$(".closed.fourth, .closed.fifth, .closed.sixth").css("top",$windowHeight95+$windowWidth/3*$ratio)}$("#hello").css("height",$windowHeight95);$(".main").css("height",$windowHeight);$(".closed.open").css("height",$windowHeight)};$(function(){$("[data-typer-targets]").typer();$resizeErrythang();$(window).resize(function(){$resizeErrythang()});$("#hello .link").click(function(){$("#about").addClass("open");
$("html, body").animate({scrollTop:$("#about").offset().top},1E3);$(".close-about").click(function(){$("#about").removeClass("open")})});var a,b=0,d;$(".thumb").scroll(function(){a=!0});setInterval(function(){if(a){var c=d.offset().top-$(window).scrollTop();c>b?(c>=-500+$(".back").outerHeight()&&$(".x").removeClass("dark"),d.find(".back.close-bottom").offset().top>$(".thumb.open").offset().top+$windowHeight&&(d.find(".back.close-top").addClass("loaded"),$(".pace-inactive").removeClass("pace-hidden"))):
d.find(".back.close-bottom").offset().top<=$(".thumb.open").offset().top+$windowHeight?(d.find(".back.close-top").removeClass("loaded"),$(".pace-inactive").addClass("pace-hidden")):c<-500+$(".back").outerHeight()&&$(".x").addClass("dark");b=c;a=!1}},250);$(".thumb").click(function(b){var a=$(this),g=a.data("project"),f=a.find(".story"),h=""+g+".php";$(b.target).hasClass("close-top")?(a.find(".back.close-top").first().removeClass("loaded"),f.animate({marginTop:-1*f.offset().top+$windowHeight},700),
$(".pace-inactive").addClass("pace-hidden"),setTimeout(function(){a.removeClass("open");a.addClass("closed");f.removeClass("open");$("body").removeClass("noScroll");$resizeErrythang();setTimeout(function(){f.html("")},200)},1E3)):$(b.target).hasClass("close-bottom")?(f.animate({marginTop:-f.height()},700),setTimeout(function(){f.html("");a.removeClass("open");$("body").removeClass("noScroll");$resizeErrythang()},1E3)):($(".story").removeClass("main"),$(".thumb").removeClass("main"),a.addClass("open"),
a.removeClass("closed"),$(".thumb.open").css("top",$(window).scrollTop()),$(".thumb.open").css("height",$windowHeight),f.removeAttr("style"),f.addClass("open"),$("body").addClass("noScroll"),d=$(".thumb.open").find(".story"),setTimeout(function(){k.restart();a.children("img").first().addClass("fixed");f.load(h);$.ajax({url:h,success:function(b){f.html(b);$(document).ajaxComplete(function(){setTimeout(function(){r.finish();a.find(".back.close-top").first().addClass("loaded");a.find(".intro").first().addClass("loaded")},
2000)})}})},1E3))})})}).call(this);